// .agents/skills/clerk-react-patterns/templates/react-basic-auth/src/App.tsx
import { Show, SignInButton, SignUpButton, UserButton } from "@clerk/react";

function App() {
  return (
    <>
      <header>
        <Show when='signed-out'>
          <SignInButton />
          <SignUpButton />
        </Show>
        <Show when='signed-in'>
          <UserButton />
        </Show>
      </header>
    </>
  );
}

export default App;

// .agents/skills/clerk-vue-patterns/templates/vue-basic-auth/src/App.vue
<script setup lang="ts">
import { Show, SignInButton, SignUpButton, UserButton } from "@clerk/vue";
</script>

<template>
  <header>
    <Show when="signed-out">
      <SignInButton />
      <SignUpButton />
    </Show>
    <Show when="signed-in">
      <UserButton />
    </Show>
  </header>
</template>
